module.exports = {
    user_created: 'User created successfully',
    success: 'Success',
    user_exists: 'User already exists',
    un_success: 'Unsuccessful',
    server_error: 'Unable to connect to server!',
    user_not_found: 'User not found!',
    invalid_password: 'Invalid Password!',
    logged_in: 'Logged In!',
    logged_out: 'Logged Out!',
    no_token_provided: 'No token provided!',
    unAuthorized: 'Un Authorized!',
    invalid_token: 'Invalid / Expired Token',
    access_denied: 'Access Denied!',
}